services:
  super-app:
    build: .
    environment:
      - MONGO_URI=mongodb://localhost:27017/83-dars
    env_file:
      - .env
    ports:
      - '5000:3000'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    volumes:
      - mongo-data:/var/lib/mongodb/data
    container_name: mongo:test
    ports:
      - '27017:27017'

volumes:
  mongo-data:
